In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 38 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 1s (13.0 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 121752 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [ ]:
import pandas as pd
import numpy as np

# 데이터 시각화
import matplotlib.pyplot as plt
import matplotlib

import seaborn as sns

In [ ]:
plt.rc('font', family='NanumBarunGothic')

In [ ]:
# 실행결과 경고메시지 출력 제외
import warnings

warnings.filterwarnings('ignore')

In [ ]:
# 데이터 구성:Series, DataFrame
import pandas as pd
# 데이터 시각화
import matplotlib.pyplot as plt
import matplotlib

## 데이터 불러오기

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
member = pd.read_csv("/content/drive/MyDrive/최강<포빅아A4>/마켓프로젝트/마켓 CSV파일모음/member_data.csv")
member.head(10)

         회원번호 조합원상태        주소 성별    연령 배송서비스신청여부 모바일알람여부 Gold_member
0  1000012800  정상회원  수지구-풍덕천동  여  58.0       미신청       .      normal
1  1000103744  정상회원   처인구-고림동  여  34.0       미신청       .      normal
2  1000122304  정상회원     광주-기타  여  38.0       미신청       .      normal
3  1000163136  정상회원   수지구-동천동  여  73.0       미신청       .      normal
4  1000281920  정상회원  수지구-풍덕천동  여  42.0        신청       .      normal
5  1000330176  정상회원   수지구-신봉동  여  64.0       미신청       .      normal
6  1000491648  정상회원   수지구-동천동  여  37.0       미신청       .      normal
7  1000508352  정상회원   기흥구-상하동  여  35.0       미신청       .      normal
8  1000565888  정상회원   수지구-상현동  여  52.0       미신청       .      normal
9  1000577024  정상회원     기타-기타  여  47.0       미신청       .      normal

In [ ]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11555 entries, 0 to 11554
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   회원번호         11555 non-null  int64
 1   조합원상태        11555 non-null  object
 2   주소           11555 non-null  object
 3   성별           11553 non-null  object
 4   연령           11553 non-null  float64
 5   배송서비스신청여부    11555 non-null  object
 6   모바일알람여부      11555 non-null  object
 7   Gold_member  11555 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 722.3+ KB

In [ ]:
# 주소 값 확인
unique_adress=member['주소'].unique()
unique_adress

array(['수지구-풍덕천동', '처인구-고림동', '광주-기타', '수지구-동천동', '수지구-신봉동', '기흥구-상하동',
       '수지구-상현동', '기타-기타', '수지구-성복동', '분당구-백현동', '분당구-판교동', '수지구-죽전동',
       '분당구-구미동', '기흥구-동백동', '수원 영통구-기타', '기흥구-보정동', '기흥구-청덕동',
       '서울 강남구-기타', '수원 팔달구-기타', '분당구-수내동', '서울 송파구-기타', '기흥구-기타',
       '기흥구-언남동', '분당구-중동', '분당구-삼평동', '기흥구-마북동', '광주-오포읍', '화성-기타',
       '분당구-정자동', '기흥구-중동', '분당구-기타', '중원구-금광동', '처인구-역북동', '수지구-기타',
       '수원 장안구-기타', '처인구-삼가동', '처인구-기타', '수정구-신흥동', '수원 권선구-기타',
       '분당구-서현동', '분당구-야탑동', '기흥구-보라동', '기흥구-구갈동', '처인구-김량장동', '처인구-이동면',
       '분당구-분당동', '기흥구-신갈동', '기흥구-영덕동', '수정구-위례(창곡)동', '하남-기타', '기흥구-죽전동',
       '처인구-모현면', '기타-금광동', '처인구-원삼면', '분당구-이매동', '분당구-금곡동', '기타-신흥동',
       '기흥구-공세동', '기흥구-상갈동', '수정구-복정동', '기흥구-서천동', '광주-산성동', '중원구-도촌동',
       '처인구-유방동', '수원 장안구-정자동', '처인구-남사면', '서울 강남구-은행동', '수원 권선구-금곡동',
       '분당구-궁내동', '수정구-기타', '중원구-성남동', '중원구-여수동', '기타-금곡동', '기타-동천동',
       '기타-비조합원', '수정구-상대원동', '중원구-상대원동', '중원구-은행동', '중원구-하대원동', '기타-중앙동',
       '기타-보라동', '기타-동백동', '기타-은행동', '화성-보라동', '중원구-산성동', '수정구-단대동',
       '분당구-율동', '기타-궁내동', '기흥구-지곡동', '처인구-마평동', '수정구-태평동', '하남-위례동',
       '기타-율동', '기타-태평동', '기타-성남동'], dtype=object)

In [ ]:
# 개수 확인 코드
city_counts = member['주소'].str.contains('영통구').sum()
print(city_counts)

216

In [ ]:
yongin = member[member['주소'].str.contains('수지구|처인구|기흥구')]
len(yongin)

8968

In [ ]:
suwon = member[member['주소'].str.contains('팔달구|영통구|장안구|권선구')]
len(suwon)

287

In [ ]:
sungnam = member[member['주소'].str.contains('수정구|분당구|중원구')]
len(sungnam)

718

In [ ]:
seoul = member[member['주소'].str.contains('서울')]
len(seoul)

268

In [ ]:
hoe = member[member['주소'].str.contains('송파구|강남구')]
len(hoe)

268

In [ ]:
gwang = member[member['주소'].str.contains('광주')]
len(gwang)

73

In [ ]:
hannam = member[member['주소'].str.contains('하남')]
len(hannam)

14

In [ ]:
hwa = member[member['주소'].str.contains('화성')]
len(hwa)

78

# 멤버 데이터 전처리

## 기타-00동인 데이터: 기타(구) 채워넣기

In [ ]:
# 변경 사전 만들기
replace_dict = {
    "기타-금광동": "중원구-금광동",
    "기타-신흥동": "수정구-신흥동",
    "기타-금곡동": "분당구-금곡동",
    "기타-동천동": "수지구-동천동",
    "기타-중앙동": "처인구-중앙동",
    "기타-보라동": "기흥구-보라동",
    "기타-동백동": "기흥구-동백동",
    "기타-은행동": "중원구-은행동",
    "기타-궁내동": "분당구-궁내동",
    "기타-율동": "분당구-율동",
    "기타-태평동": "수정구-태평동",
    "기타-성남동": "중원구-성남동",
    "서울 강남구-은행동": "중원구-은행동"
}

# 변경된 주소값으로 '주소' 열 값 변경
member['주소'] = member['주소'].replace(replace_dict)

## 멤버 데이터 null값 대체

In [ ]:
member.isnull().sum()

회원번호           0
조합원상태          0
주소             0
성별             2
연령             2
배송서비스신청여부      0
모바일알람여부        0
Gold_member    0
dtype: int64

In [ ]:
# '성별' 열의 결측치를 최빈값으로 대체
mode_gender = member['성별'].mode()[0]
member['성별'] = member['성별'].fillna(mode_gender)

# '연령' 열의 결측치를 최빈값으로 대체
mode_age = member['연령'].mode()[0]
member['연령'] = member['연령'].fillna(mode_age)

In [ ]:
# 결측치 재확인
member.isnull().sum()

회원번호           0
조합원상태          0
주소             0
성별             0
연령             0
배송서비스신청여부      0
모바일알람여부        0
Gold_member    0
dtype: int64

# 시 파생변수 생성

In [ ]:
# 시로 파생변수 생성
# '시'열을 추가
member['시'] = ''

# '주소'열을 기반으로 '시'열 값 설정
for index, row in member.iterrows():
    구, 동 = row['주소'].split('-')
    구 = 구.split()[-1]
    if 구 in ['영통구', '팔달구', '장안구', '권선구']:
        member.at[index, '시'] = '수원'
    elif 구 in ['수지구', '처인구', '기흥구']:
        member.at[index, '시'] = '용인'
    elif 구 in ['수정구', '분당구', '중원구']:
        member.at[index, '시'] = '성남'
    elif 구 == '광주':
        member.at[index, '시'] = '광주'
    elif 구 == '하남':
        member.at[index, '시'] = '하남'
    elif 구 == '화성':
        member.at[index, '시'] = '화성'
    elif 구 in ['강남구', '송파구']:
        member.at[index, '시'] = '서울'
    elif 구 in ['기타']:
        member.at[index, '시'] = '기타'


# '시'열을 주소 열 왼쪽에 삽입
member.insert(2, '시', member.pop('시'))

# '시' 열에 결측값 있는지 확인
member.isnull().sum()

회원번호           0
조합원상태          0
시              0
주소             0
성별             0
연령             0
배송서비스신청여부      0
모바일알람여부        0
Gold_member    0
dtype: int64

In [ ]:
# '주소'열을 기반으로 구와 동 정보만 남기기
for index, row in member.iterrows():
    split_address = row['주소'].split('-')
    # 시 정보가 포함된 경우 시 정보를 제거한 후, 구와 동 정보만 남기기
    split_address = split_address[0].split()
    if len(split_address) == 2:
        member.at[index, '주소'] = split_address[-1]

In [ ]:
# test
test=['서울 송파구-방이동','처인구-우포읍']
# '주소'열을 기반으로 구와 동 정보만 남기기
for address in test:
    split_test = address.split('-')
    print(split_test)
    # 시 정보가 포함된 경우 시 정보를 제거한 후, 구와 동 정보만 남기기
    split_test = split_test[0].split()
    print(split_test)
    if len(split_test) == 2:
        print(split_test[-1])

['서울 송파구', '방이동']
['서울', '송파구']
송파구
['처인구', '우포읍']
['처인구']

In [ ]:
# 주소 값 확인
unique_adress=member['시'].unique()
unique_adress
# 용인 , 수원 , 성남, 광주, 하남, 화성, 서울 으로 나뉘어야함

array(['용인', '광주', '기타', '성남', '수원', '서울', '화성', '하남'], dtype=object)

In [ ]:
# 시별로 잘 나뉘어졌는지 확인
def count_city_values(df):
    return df['시'].value_counts()

# 함수 호출 예시
city_counts = count_city_values(member)
print(city_counts)

용인    8981
기타    1127
성남     728
수원     287
서울     267
화성      78
광주      73
하남      14
Name: 시, dtype: int64

# 연령대 파생변수 생성

In [ ]:
# 20대 이하/30대/40대/50대/60대/70대/80대 이상
def get_age_group(age):
    if age <= 20:
        return '20대 이하'
    elif age < 30:
        return '20대'
    elif age < 40:
        return '30대'
    elif age < 50:
        return '40대'
    elif age < 60:
        return '50대'
    elif age < 70:
        return '60대'
    elif age < 80:
        return '70대'
    else:
        return '80대 이상'

# '연령' 열을 기반으로 '연령대' 열을 추가
member['연령대'] = member['연령'].apply(get_age_group)

# '연령대'열을 주소 열 왼쪽에 삽입
member.insert(6, '연령대', member.pop('연령대'))

# 결과 출력
member

,회원번호,조합원상태,시,주소,성별,연령,연령대,배송서비스신청여부,모바일알람여부,Gold_member
0,1000012800,정상회원,용인,수지구-풍덕천동,여,58.0,50대,미신청,.,normal
1,1000103744,정상회원,용인,처인구-고림동,여,34.0,30대,미신청,.,normal
2,1000122304,정상회원,광주,광주-기타,여,38.0,30대,미신청,.,normal
3,1000163136,정상회원,용인,수지구-동천동,여,73.0,70대,미신청,.,normal
4,1000281920,정상회원,용인,수지구-풍덕천동,여,42.0,40대,신청,.,normal
...,...,...,...,...,...,...,...,...,...,...
11550,999682432,탈퇴,용인,수지구-동천동,여,47.0,40대,미신청,.,normal
11551,999721408,정상회원,용인,수지구-동천동,여,43.0,40대,미신청,.,normal
11552,999738112,정상회원,용인,수지구-성복동,여,67.0,60대,미신청,.,normal
11553,999754816,정상회원,용인,수지구-상현동,여,44.0,40대,신청,.,normal
11554,99995712,정상회원,용인,수지구-상현동,여,66.0,60대,미신청,.,normal

In [ ]:
import pandas as pd


# CSV 파일로 저장
member.to_csv('finmem.csv', index=False)

print("finmem.csv 파일이 성공적으로 저장되었습니다.")

finmem.csv 파일이 성공적으로 저장되었습니다.

In [ ]:
# '주소' 열의 고유값 가져오기
unique_values = member['주소'].unique()
unique_values

array(['수지구-풍덕천동', '처인구-고림동', '광주-기타', '수지구-동천동', '수지구-신봉동', '기흥구-상하동',
       '수지구-상현동', '기타-기타', '수지구-성복동', '분당구-백현동', '분당구-판교동', '수지구-죽전동',
       '분당구-구미동', '기흥구-동백동', '영통구', '기흥구-보정동', '기흥구-청덕동', '강남구', '팔달구',
       '분당구-수내동', '송파구', '기흥구-기타', '기흥구-언남동', '분당구-중동', '분당구-삼평동',
       '기흥구-마북동', '광주-오포읍', '화성-기타', '분당구-정자동', '기흥구-중동', '분당구-기타',
       '중원구-금광동', '처인구-역북동', '수지구-기타', '장안구', '처인구-삼가동', '처인구-기타',
       '수정구-신흥동', '권선구', '분당구-서현동', '분당구-야탑동', '기흥구-보라동', '기흥구-구갈동',
       '처인구-김량장동', '처인구-이동면', '분당구-분당동', '기흥구-신갈동', '기흥구-영덕동',
       '수정구-위례(창곡)동', '하남-기타', '기흥구-죽전동', '처인구-모현면', '처인구-원삼면', '분당구-이매동',
       '분당구-금곡동', '기흥구-공세동', '기흥구-상갈동', '수정구-복정동', '기흥구-서천동', '광주-산성동',
       '중원구-도촌동', '처인구-유방동', '처인구-남사면', '중원구-은행동', '분당구-궁내동', '수정구-기타',
       '중원구-성남동', '중원구-여수동', '기타-비조합원', '수정구-상대원동', '중원구-상대원동',
       '중원구-하대원동', '처인구-중앙동', '화성-보라동', '중원구-산성동', '수정구-단대동', '분당구-율동',
       '기흥구-지곡동', '처인구-마평동', '수정구-태평동', '하남-위례동'], dtype=object)

In [ ]:
count_odd = member['주소'].isin(['송파구', '강남구', '팔달구', '장안구', '영통구']).sum()
print(count_odd)

536

In [ ]:
# "-기타"로 된 값만 추출
etc_values = [value for value in unique_values if "기타-" in value]
etc_values

['기타-기타', '기타-비조합원']

In [ ]:
# Define the list of addresses
addresses_to_extract = ['광주-기타',
 '기타-기타',
 '수원 영통구-기타',
 '서울 강남구-기타',
 '수원 팔달구-기타',
 '서울 송파구-기타',
 '기흥구-기타',
 '화성-기타',
 '분당구-기타',
 '수지구-기타',
 '수원 장안구-기타',
 '처인구-기타',
 '수원 권선구-기타',
 '하남-기타',
 '수정구-기타']

# Extract rows with specified addresses
selected_rows = member[member['주소'].isin(addresses_to_extract)]

# Display the selected rows
print(selected_rows)

             회원번호 조합원상태         주소 성별    연령 배송서비스신청여부 모바일알람여부 Gold_member
2      1000122304  정상회원      광주-기타  여  38.0       미신청       .      normal
9      1000577024  정상회원      기타-기타  여  47.0       미신청       .      normal
24     1001776000  정상회원      기타-기타  남  57.0       미신청       .      normal
32     1003019520  정상회원      기타-기타  여  72.0       미신청       .      normal
33     1003088192  정상회원      기타-기타  여  66.0       미신청       .      normal
...           ...   ...        ... ..   ...       ...     ...         ...
11519   998470464  정상회원      기타-기타  여  42.0       미신청       .      normal
11524   998583680  정상회원  서울 강남구-기타  여  43.0       미신청       .      normal
11538   999398464  정상회원      기타-기타  여  54.0       미신청       .      normal
11539   999474560  정상회원      기타-기타  여  40.0       미신청       .      normal
11549   999654592  정상회원      기타-기타  여  47.0       미신청       .      normal

[1925 rows x 8 columns]

In [ ]:
# Count the occurrences of each unique value in the '주소' column
address_counts = selected_rows['주소'].value_counts()

# Display the counts
print(address_counts)

수지구-풍덕천동    3188
수지구-상현동     1601
수지구-신봉동     1422
기타-기타       1126
수지구-동천동      925
            ...
기타-비조합원        1
처인구-남사면        1
수정구-복정동        1
중원구-산성동        1
하남-위례동         1
Name: 주소, Length: 81, dtype: int64

In [ ]:
# "면"으로 된 값만 추출
etc_values = [value for value in unique_values if "면" in value]
etc_values

['처인구-이동면', '처인구-모현면', '처인구-원삼면', '처인구-남사면']

In [ ]:
# "읍"으로 된 값만 추출
etc_values = [value for value in unique_values if "읍" in value]
etc_values

['광주-오포읍']

In [ ]:
# Define the list of addresses
addresses_to_extract = ['처인구-이동면', '처인구-모현면', '처인구-원삼면', '처인구-남사면', '광주-오포읍']

# Extract rows with specified addresses
selected_rows = member[member['주소'].isin(addresses_to_extract)]

# Display the selected rows
print(selected_rows)

             회원번호 조합원상태       주소 성별    연령 배송서비스신청여부 모바일알람여부 Gold_member
238    1019894272  정상회원   광주-오포읍  여  36.0       미신청       .      normal
819    1096524800  정상회원   광주-오포읍  남  51.0       미신청       .      normal
827    1098035584  정상회원  처인구-이동면  여  40.0       미신청       .      normal
1113   1138724672  정상회원  처인구-모현면  여  42.0       미신청       .      normal
1142   1144533952  정상회원   광주-오포읍  여  39.0       미신청       .      normal
1145   1144947840  정상회원  처인구-모현면  여  37.0       미신청       .      normal
1165   1147488704  정상회원  처인구-원삼면  여  46.0       미신청       .      normal
1526   1200625984  정상회원   광주-오포읍  남  36.0       미신청       .      normal
1819   1239420096  정상회원   광주-오포읍  여  34.0       미신청       .      normal
1887   1248505216  정상회원   광주-오포읍  여  31.0       미신청       .      normal
2478   1332461376  정상회원   광주-오포읍  여  36.0       미신청      수신      normal
2584   1349440064  정상회원  처인구-모현면  남  33.0        신청       .      normal
2797   1381535872  정상회원  처인구-남사면  여  38.0       미신청       .      normal
3076    144730880  정상회원   광주-오포읍  여  61.0       미신청       .      normal
3235   1469926016  정상회원   광주-오포읍  여  32.0       미신청       .      normal
3452   1500505472  정상회원   광주-오포읍  여  42.0       미신청       .      normal
3492   1504417920  정상회원   광주-오포읍  여  33.0       미신청       .      normal
3494   1504978432  정상회원  처인구-모현면  여  38.0       미신청       .      normal
3641   1523900352  정상회원   광주-오포읍  여  40.0       미신청       .      normal
3785   1539088000  정상회원   광주-오포읍  여  36.0       미신청       .      normal
3912   1554606016  정상회원  처인구-원삼면  여  40.0       미신청       .      normal
4700    195227072  정상회원   광주-오포읍  여  65.0       미신청       .      normal
4718    198224512  정상회원  처인구-모현면  여  43.0       미신청       .      normal
4906    223961664  정상회원   광주-오포읍  여  50.0       미신청       .      normal
5121    255101632  정상회원   광주-오포읍  여  56.0       미신청       .      normal
5143    260263168  정상회원  처인구-원삼면  여  61.0       미신청       .      normal
5332    279522880  정상회원   광주-오포읍  여  51.0       미신청       .      normal
5599    319148480  정상회원   광주-오포읍  남  64.0       미신청       .      normal
6292    422694720  정상회원  처인구-모현면  여  37.0       미신청       .      normal
6545    453361408  정상회원   광주-오포읍  여  42.0       미신청       .      normal
7028     53465792  정상회원   광주-오포읍  여  67.0       미신청       .      normal
7305    566738880  정상회원   광주-오포읍  여  69.0       미신청      수신      normal
7319    567676160  정상회원   광주-오포읍  남  39.0       미신청       .      normal
7749     61713856  정상회원  처인구-모현면  여  68.0       미신청       .      normal
8526    706274816  정상회원  처인구-모현면  여  40.0       미신청       .      normal
8741    732288512  정상회원   광주-오포읍  여  40.0       미신청       .      normal
8760    734870208  정상회원   광주-오포읍  여  61.0       미신청       .      normal
8976    745570048  정상회원   광주-오포읍  여  72.0       미신청       .      normal
8993    745913408  정상회원   광주-오포읍  여  53.0       미신청       .      normal
9015    746299456  정상회원   광주-오포읍  남  70.0       미신청      수신      normal
9064    747266432  정상회원   광주-오포읍  여  51.0       미신청       .      normal
9472    763898048  정상회원   광주-오포읍  여  49.0       미신청       .      normal
9596    767032832  정상회원   광주-오포읍  여  49.0       미신청       .      normal
10484   852499776  정상회원  처인구-원삼면  여  48.0       미신청       .      normal
10863   895241600  정상회원  처인구-모현면  여  42.0       미신청       .      normal
11497   995918464  정상회원   광주-오포읍  여  39.0       미신청       .      normal

In [ ]:
# Define the list of addresses
addresses_to_extract = ['처인구-이동면', '처인구-모현면', '처인구-원삼면', '처인구-남사면', '광주-오포읍']

# Filter rows with specified addresses
selected_rows = member[member['주소'].isin(addresses_to_extract)]

# Sort the selected rows based on the '주소' column
selected_rows_sorted = selected_rows.sort_values(by='주소')

# Display the sorted and filtered DataFrame
print(selected_rows_sorted)

             회원번호 조합원상태       주소 성별    연령 배송서비스신청여부 모바일알람여부 Gold_member
238    1019894272  정상회원   광주-오포읍  여  36.0       미신청       .      normal
4906    223961664  정상회원   광주-오포읍  여  50.0       미신청       .      normal
5121    255101632  정상회원   광주-오포읍  여  56.0       미신청       .      normal
5332    279522880  정상회원   광주-오포읍  여  51.0       미신청       .      normal
5599    319148480  정상회원   광주-오포읍  남  64.0       미신청       .      normal
6545    453361408  정상회원   광주-오포읍  여  42.0       미신청       .      normal
7028     53465792  정상회원   광주-오포읍  여  67.0       미신청       .      normal
7305    566738880  정상회원   광주-오포읍  여  69.0       미신청      수신      normal
4700    195227072  정상회원   광주-오포읍  여  65.0       미신청       .      normal
7319    567676160  정상회원   광주-오포읍  남  39.0       미신청       .      normal
8760    734870208  정상회원   광주-오포읍  여  61.0       미신청       .      normal
8976    745570048  정상회원   광주-오포읍  여  72.0       미신청       .      normal
8993    745913408  정상회원   광주-오포읍  여  53.0       미신청       .      normal
9015    746299456  정상회원   광주-오포읍  남  70.0       미신청      수신      normal
9064    747266432  정상회원   광주-오포읍  여  51.0       미신청       .      normal
9472    763898048  정상회원   광주-오포읍  여  49.0       미신청       .      normal
9596    767032832  정상회원   광주-오포읍  여  49.0       미신청       .      normal
8741    732288512  정상회원   광주-오포읍  여  40.0       미신청       .      normal
3785   1539088000  정상회원   광주-오포읍  여  36.0       미신청       .      normal
11497   995918464  정상회원   광주-오포읍  여  39.0       미신청       .      normal
1887   1248505216  정상회원   광주-오포읍  여  31.0       미신청       .      normal
819    1096524800  정상회원   광주-오포읍  남  51.0       미신청       .      normal
3492   1504417920  정상회원   광주-오포읍  여  33.0       미신청       .      normal
3452   1500505472  정상회원   광주-오포읍  여  42.0       미신청       .      normal
1142   1144533952  정상회원   광주-오포읍  여  39.0       미신청       .      normal
3235   1469926016  정상회원   광주-오포읍  여  32.0       미신청       .      normal
3076    144730880  정상회원   광주-오포읍  여  61.0       미신청       .      normal
1526   1200625984  정상회원   광주-오포읍  남  36.0       미신청       .      normal
2478   1332461376  정상회원   광주-오포읍  여  36.0       미신청      수신      normal
3641   1523900352  정상회원   광주-오포읍  여  40.0       미신청       .      normal
1819   1239420096  정상회원   광주-오포읍  여  34.0       미신청       .      normal
2797   1381535872  정상회원  처인구-남사면  여  38.0       미신청       .      normal
1113   1138724672  정상회원  처인구-모현면  여  42.0       미신청       .      normal
1145   1144947840  정상회원  처인구-모현면  여  37.0       미신청       .      normal
4718    198224512  정상회원  처인구-모현면  여  43.0       미신청       .      normal
7749     61713856  정상회원  처인구-모현면  여  68.0       미신청       .      normal
2584   1349440064  정상회원  처인구-모현면  남  33.0        신청       .      normal
6292    422694720  정상회원  처인구-모현면  여  37.0       미신청       .      normal
10863   895241600  정상회원  처인구-모현면  여  42.0       미신청       .      normal
3494   1504978432  정상회원  처인구-모현면  여  38.0       미신청       .      normal
8526    706274816  정상회원  처인구-모현면  여  40.0       미신청       .      normal
1165   1147488704  정상회원  처인구-원삼면  여  46.0       미신청       .      normal
5143    260263168  정상회원  처인구-원삼면  여  61.0       미신청       .      normal
10484   852499776  정상회원  처인구-원삼면  여  48.0       미신청       .      normal
3912   1554606016  정상회원  처인구-원삼면  여  40.0       미신청       .      normal
827    1098035584  정상회원  처인구-이동면  여  40.0       미신청       .      normal

In [ ]:
selected_rows_sorted.count_value()

In [ ]:
# Count the occurrences of each unique value in the '주소' column
address_counts = selected_rows_sorted['주소'].value_counts()

# Display the counts
print(address_counts)

광주-오포읍     31
처인구-모현면     9
처인구-원삼면     4
처인구-남사면     1
처인구-이동면     1
Name: 주소, dtype: int64

In [ ]:
# import pandas as pd


# # CSV 파일로 저장
# member.to_csv('adr_member.csv', index=False)

# print("adr_member.csv 파일이 성공적으로 저장되었습니다.")

adr_member.csv 파일이 성공적으로 저장되었습니다.

In [ ]:
# "-기타"로 된 값만 추출
etc_values = [value for value in unique_values if "기타-" in value]
etc_values

['기타-기타', '기타-비조합원']


기타-기타
기타-금광동 중원구-금광동
기타-신흥동 수정구-신흥동
기타-금곡동 분당구-금곡동
기타-동천동 수지구-동천동
기타-비조합원
기타-중앙동 처인구-중앙동
기타-보라동 기흥구-보라동
기타-동백동 기흥구-동백동
기타-은행동 중원구-은행동
기타-궁내동 분당구-궁내동
기타-율동   분당구-율동
기타-태평동 수정구-태평동
기타-성남동 중원구-성남동